stages:
  - prepare
  - linters
  - tests
  - deploy_dev

.cache-tpl: &cache-tpl
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules
    - frontend/components
  policy: pull

.test-template: &test-template
  image: node:10-stretch

  tags:
    - docker
  cache:
    <<: *cache-tpl
  before_script:
    - npm install -g grunt-cli
    - 'echo "INFO: NB node packages : $(ls node_modules | wc -l)"'
    - 'echo "INFO: NB bower packages : $(ls frontend/components | wc -l)"'
  except:
    variables:
      - $SKIP_TESTS

prepare:
  image: node:10-stretch
  stage: prepare
  tags:
    - docker
  cache:
    <<: *cache-tpl
    policy: pull-push
  script:
    - npm install
    - npm install -g bower
    - bower install --allow-root
    - 'echo "INFO: NB node packages : $(ls node_modules | wc -l)"'
    - 'echo "INFO: NB bower packages : $(ls frontend/components | wc -l)"'
  except:
    variables:
      - $SKIP_PREPARE

linters:
  <<: *test-template
  stage: linters
  script:
    - grunt -v linters
  except:
    variables:
      - $SKIP_LINTERS

test-unit-frontend:
  <<: *test-template
  stage: tests
  script:
    - grunt -v test-unit-frontend

test-unit-backend:
  <<: *test-template
  stage: tests
  script:
    - grunt -v test-unit-backend

deploy_dev:
  stage: deploy_dev
  tags:
    - dev.open-paas.org
    - deployment
  variables:
    GIT_STRATEGY: none
  environment:
    name: dev
    url: https://dev.open-paas.org
  only:
    - master@linagora/lgs/openpaas/linagora.esn.contact.collect
  script:
    - cd /srv/${CI_PROJECT_NAME}
    - git fetch --all
    - git checkout ${CI_COMMIT_SHA}
    - npm install --production
    - npm update --production
    - npm prune
    - bower install --production
    - bower prune
    - git checkout -- .
    - sudo /etc/init.d/rse.dev restart
